"""Add employees table

Revision ID: 4d50c1f0013c
Revises: ce3f6d2a5dfe
Create Date: 2025-08-03 18:14:07.533810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d50c1f0013c'
down_revision: Union[str, Sequence[str], None] = 'ce3f6d2a5dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
